import unreal as u
ROOT='/Game/MineLearning/VFX/RadiantDissolve'
bp=u.load_asset(ROOT+'/BP_RadiantDissolve_Test')
level=u.get_editor_subsystem(u.LevelEditorSubsystem)
map_path=ROOT+'/L_RadiantDissolve_Test'
assert level.get_current_level().get_outer().get_path_name() == map_path+'.L_RadiantDissolve_Test', 'Refusing to write outside the independent demo map'
actors=u.get_editor_subsystem(u.EditorActorSubsystem)
def spawn(cls,name,loc,rot=u.Rotator()):
    a=next((a for a in actors.get_all_level_actors() if a.get_actor_label()==name),None)
    if not a:a=actors.spawn_actor_from_class(cls,loc,rot);a.set_actor_label(name)
    a.set_actor_location_and_rotation(loc,rot,False,True)
    return a
target=spawn(bp.generated_class(),'RadiantDissolve_Test',u.Vector(0,0,0))
target.set_editor_property('PropagationDistance',135.)
target.set_editor_property('PreviewTime',0.)
cam=spawn(u.CameraActor,'DemoCamera',u.Vector(-200,-260,165),u.Rotator(pitch=-22,yaw=52.4,roll=0))
cam.camera_component.set_field_of_view(38)
cam.set_editor_property('auto_activate_for_player',u.AutoReceiveInput.PLAYER0)
floor=spawn(u.StaticMeshActor,'NeutralStage',u.Vector(0,0,-7))
floor.static_mesh_component.set_static_mesh(u.load_asset('/Engine/BasicShapes/Cylinder'))
floor.set_actor_scale3d(u.Vector(2.1,2.1,.12))
floor.static_mesh_component.set_material(0,u.load_asset('/Engine/EngineMaterials/DefaultMaterial'))
ground=spawn(u.StaticMeshActor,'StudioFloor',u.Vector(0,0,-15))
ground.static_mesh_component.set_static_mesh(u.load_asset('/Engine/BasicShapes/Plane'))
ground.set_actor_scale3d(u.Vector(30,30,1))
light=spawn(u.DirectionalLight,'KeyLight',u.Vector(0,0,240),u.Rotator(pitch=-45,yaw=-30,roll=0))
light.light_component.set_intensity(3.)
fill=spawn(u.RectLight,'SoftFill',u.Vector(-90,-140,110),u.Rotator(pitch=-25,yaw=50,roll=0))
fill.light_component.set_intensity(1500.)
pp=spawn(u.PostProcessVolume,'DemoExposure',u.Vector())
pp.set_editor_property('unbound',True)
settings=pp.get_editor_property('settings')
settings.set_editor_property('override_auto_exposure_method',True)
settings.set_editor_property('auto_exposure_method',u.AutoExposureMethod.AEM_MANUAL)
settings.set_editor_property('override_auto_exposure_bias',True)
settings.set_editor_property('auto_exposure_bias',9.)
settings.set_editor_property('override_bloom_intensity',True)
settings.set_editor_property('bloom_intensity',.35)
settings.set_editor_property('override_motion_blur_amount',True)
settings.set_editor_property('motion_blur_amount',0.)
pp.set_editor_property('settings',settings)
world=level.get_current_level().get_outer()
ws=world.get_world_settings()
ws.set_editor_property('default_game_mode',u.GameModeBase.static_class())
u.EditorLevelLibrary.set_level_viewport_camera_info(cam.get_actor_location(),cam.get_actor_rotation())
level.save_current_level()
print('RADIANT_DEMO_BUILT')


